// 權限名稱常數（純 string；前後端對齊 utils/permissions.py Permission(str, Enum)）
// 取代舊版的 PERMISSION_VALUES（number map）— 因後端從 bigint mask 改為 text[]
export const PERMISSION_NAMES = {
  DASHBOARD: 'DASHBOARD',
  APPROVALS: 'APPROVALS',
  CALENDAR: 'CALENDAR',
  SCHEDULE: 'SCHEDULE',
  MEETINGS: 'MEETINGS',
  REPORTS: 'REPORTS',
  AUDIT_LOGS: 'AUDIT_LOGS',
  ATTENDANCE_READ: 'ATTENDANCE_READ',
  ATTENDANCE_WRITE: 'ATTENDANCE_WRITE',
  LEAVES_READ: 'LEAVES_READ',
  LEAVES_WRITE: 'LEAVES_WRITE',
  OVERTIME_READ: 'OVERTIME_READ',
  OVERTIME_WRITE: 'OVERTIME_WRITE',
  EMPLOYEES_READ: 'EMPLOYEES_READ',
  EMPLOYEES_WRITE: 'EMPLOYEES_WRITE',
  STUDENTS_READ: 'STUDENTS_READ',
  STUDENTS_WRITE: 'STUDENTS_WRITE',
  CLASSROOMS_READ: 'CLASSROOMS_READ',
  CLASSROOMS_WRITE: 'CLASSROOMS_WRITE',
  SALARY_READ: 'SALARY_READ',
  SALARY_WRITE: 'SALARY_WRITE',
  ANNOUNCEMENTS_READ: 'ANNOUNCEMENTS_READ',
  ANNOUNCEMENTS_WRITE: 'ANNOUNCEMENTS_WRITE',
  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_WRITE: 'SETTINGS_WRITE',
  USER_MANAGEMENT_READ: 'USER_MANAGEMENT_READ',
  USER_MANAGEMENT_WRITE: 'USER_MANAGEMENT_WRITE',
  ACTIVITY_READ: 'ACTIVITY_READ',
  ACTIVITY_WRITE: 'ACTIVITY_WRITE',
  DISMISSAL_CALLS_READ: 'DISMISSAL_CALLS_READ',
  DISMISSAL_CALLS_WRITE: 'DISMISSAL_CALLS_WRITE',
  FEES_READ: 'FEES_READ',
  FEES_WRITE: 'FEES_WRITE',
  RECRUITMENT_READ: 'RECRUITMENT_READ',
  RECRUITMENT_WRITE: 'RECRUITMENT_WRITE',
  ACTIVITY_PAYMENT_APPROVE: 'ACTIVITY_PAYMENT_APPROVE',
  STUDENTS_LIFECYCLE_WRITE: 'STUDENTS_LIFECYCLE_WRITE',
  GUARDIANS_READ: 'GUARDIANS_READ',
  GUARDIANS_WRITE: 'GUARDIANS_WRITE',
  RECRUITMENT_CONVERT: 'RECRUITMENT_CONVERT',
  BUSINESS_ANALYTICS: 'BUSINESS_ANALYTICS',
  PORTFOLIO_READ: 'PORTFOLIO_READ',
  PORTFOLIO_WRITE: 'PORTFOLIO_WRITE',
  PORTFOLIO_PUBLISH: 'PORTFOLIO_PUBLISH',
  STUDENTS_HEALTH_READ: 'STUDENTS_HEALTH_READ',
  STUDENTS_HEALTH_WRITE: 'STUDENTS_HEALTH_WRITE',
  STUDENTS_MEDICATION_ADMINISTER: 'STUDENTS_MEDICATION_ADMINISTER',
  STUDENTS_SPECIAL_NEEDS_READ: 'STUDENTS_SPECIAL_NEEDS_READ',
  STUDENTS_SPECIAL_NEEDS_WRITE: 'STUDENTS_SPECIAL_NEEDS_WRITE',
  PARENT_MESSAGES_WRITE: 'PARENT_MESSAGES_WRITE',
  GOV_REPORTS_VIEW: 'GOV_REPORTS_VIEW',
  GOV_REPORTS_EXPORT: 'GOV_REPORTS_EXPORT',
  APPRAISAL_READ: 'APPRAISAL_READ',
  APPRAISAL_EVENT_WRITE: 'APPRAISAL_EVENT_WRITE',
  APPRAISAL_REVIEW: 'APPRAISAL_REVIEW',
  APPRAISAL_ACCOUNTING: 'APPRAISAL_ACCOUNTING',
  APPRAISAL_FINALIZE: 'APPRAISAL_FINALIZE',
  APPRAISAL_RULE_WRITE: 'APPRAISAL_RULE_WRITE',
  YEAR_END_READ: 'YEAR_END_READ',
  YEAR_END_WRITE: 'YEAR_END_WRITE',
  YEAR_END_FINALIZE: 'YEAR_END_FINALIZE',
  VENDOR_PAYMENT_READ: 'VENDOR_PAYMENT_READ',
  VENDOR_PAYMENT_WRITE: 'VENDOR_PAYMENT_WRITE',
} as const

export type PermissionName = typeof PERMISSION_NAMES[keyof typeof PERMISSION_NAMES]

export const ROUTE_PERMISSION_RULES = [
  { path: '/', permission: 'DASHBOARD' },
  { path: '/approvals', permission: 'APPROVALS' },
  { path: '/calendar', permission: 'CALENDAR' },
  { path: '/schedule', permission: 'SCHEDULE' },
  { path: '/attendance', permission: 'ATTENDANCE_READ' },
  { path: '/leaves', permission: 'LEAVES_READ' },
  { path: '/meetings', permission: 'MEETINGS' },
  { path: '/employees', permission: 'EMPLOYEES_READ' },
  { path: '/students', permission: 'STUDENTS_READ' },
  { path: '/students/profile', permission: 'STUDENTS_READ', prefix: true },
  { path: '/student-attendance', permission: 'STUDENTS_READ' },
  { path: '/student-leaves', permission: 'STUDENTS_READ' },
  { path: '/student-assessments', permission: 'STUDENTS_READ' },
  { path: '/student-incidents', permission: 'STUDENTS_READ' },
  { path: '/student-academic-affairs', permission: 'STUDENTS_READ' },
  { path: '/classrooms', permission: 'CLASSROOMS_READ' },
  { path: '/salary', permission: 'SALARY_READ' },
  { path: '/announcements', permission: 'ANNOUNCEMENTS_READ' },
  { path: '/reports', permission: 'REPORTS' },
  { path: '/gov-reports', permission: 'REPORTS' },
  // /admin/gov-reports/{monthly,certificates,subsidies,iep} 對齊後端 GOV_REPORTS_VIEW 守衛
  { path: '/admin/gov-reports', permission: 'GOV_REPORTS_VIEW', prefix: true },
  { path: '/audit-logs', permission: 'AUDIT_LOGS' },
  { path: '/settings', permission: 'SETTINGS_READ' },
  { path: '/dismissal-queue', permission: 'DISMISSAL_CALLS_READ' },
  { path: '/activity/dashboard', permission: 'ACTIVITY_READ' },
  { path: '/activity/registrations', permission: 'ACTIVITY_READ' },
  { path: '/activity/registrations/pending', permission: 'ACTIVITY_PAYMENT_APPROVE' },
  { path: '/activity/pos', permission: 'ACTIVITY_WRITE' },
  { path: '/activity/pos/approval', permission: 'ACTIVITY_PAYMENT_APPROVE' },
  { path: '/activity/catalog', permission: 'ACTIVITY_READ' },
  { path: '/activity/courses', permission: 'ACTIVITY_READ' },
  { path: '/activity/supplies', permission: 'ACTIVITY_READ' },
  { path: '/activity/inquiries', permission: 'ACTIVITY_READ' },
  { path: '/activity/settings', permission: 'ACTIVITY_WRITE' },
  { path: '/activity/changes', permission: 'ACTIVITY_READ' },
  { path: '/activity/attendance', permission: 'ACTIVITY_READ', prefix: true },
  { path: '/fees', permission: 'FEES_READ' },
  { path: '/student-enrollment', permission: 'STUDENTS_READ' },
  { path: '/recruitment', permission: 'RECRUITMENT_READ' },
  { path: '/recruitment-ivykids', permission: 'RECRUITMENT_READ' },
  { path: '/analytics', permission: 'BUSINESS_ANALYTICS', prefix: true },
  { path: '/portfolio/medication-today', permission: 'STUDENTS_HEALTH_READ' },
  // 考核：navigation gate 暫掛 SETTINGS_READ；後端 router 用 APPRAISAL_* 細粒度守衛
  { path: '/appraisal', permission: 'SETTINGS_READ', prefix: true },
  // 考核管理整合頁（顯示 SETTINGS_READ 或 SALARY_READ 任一即可）
  { path: '/appraisal-management', permission: 'SETTINGS_READ' },
  { path: '/appraisal-management', permission: 'SALARY_READ' },
  // 年終獎金結算：navigation gate 用 YEAR_END_READ；後端 router 用 YEAR_END_* 細粒度守衛
  { path: '/year_end', permission: 'YEAR_END_READ', prefix: true },
  // 考核年終 payout（路徑為 hyphen 與 /year_end 不同）：對齊後端 APPRAISAL_FINALIZE 守衛
  { path: '/year-end/appraisal-payout', permission: 'APPRAISAL_FINALIZE' },
  // 離職管理（路徑 /admin/offboarding 獨立 prefix，沿用 EMPLOYEES_READ 為 navigation gate）
  { path: '/admin/offboarding', permission: 'EMPLOYEES_READ' },
  // 加班 / 會議整合頁（OVERTIME_READ 或 MEETINGS 任一）
  { path: '/overtime', permission: 'OVERTIME_READ' },
  { path: '/overtime', permission: 'MEETINGS' },
  // 廠商付款簽收（園務行政）
  { path: '/vendor-payments', permission: 'VENDOR_PAYMENT_READ' },
]

// 不需要權限即可訪問的路由（登入頁、密碼變更、公開報名頁、已登入即可訪問的個人資料頁等）。
// canAccessRoute 改為 default-deny，未匹配 ROUTE_PERMISSION_RULES 又不在此清單者一律拒絕，
// 避免「忘記補規則 → 直接打 URL 進頁面」的隱性後門。
// 註：/profile 在 canAccessRoute 開頭 `if (!userInfo) return false` 已守住未登入，
// 收進此清單表達「已登入即可訪問、無需 permission gate」語意。
export const PUBLIC_ROUTES = ['/login', '/change-password', '/portal/login', '/profile']
export const PUBLIC_ROUTE_PREFIXES = ['/public/']

export const TEACHER_PORTAL_ROUTES = [
  '/portal',
  '/portal/attendance',
  '/portal/leave',
  '/portal/overtime',
  '/portal/schedule',
  '/portal/anomalies',
  '/portal/students',
  '/portal/calendar',
  '/portal/salary',
  '/portal/announcements',
  '/portal/profile',
]
