// 權限位元值對照表（讀寫分離版）
// 32-bit 有符號整數（≥ 1<<31）會溢位，使用 2 ** N 儲存；
// 檢查權限時需以 BigInt 運算避免 32-bit AND 失真。
export const PERMISSION_VALUES = {
  // 不拆分的模組
  DASHBOARD: 1 << 0,
  APPROVALS: 1 << 1,
  CALENDAR: 1 << 2,
  SCHEDULE: 1 << 3,
  MEETINGS: 1 << 7,
  REPORTS: 1 << 13,
  AUDIT_LOGS: 1 << 14,
  // 讀寫分離模組
  ATTENDANCE_READ: 1 << 4,
  ATTENDANCE_WRITE: 1 << 17,
  LEAVES_READ: 1 << 5,
  LEAVES_WRITE: 1 << 18,
  OVERTIME_READ: 1 << 6,
  OVERTIME_WRITE: 1 << 19,
  EMPLOYEES_READ: 1 << 8,
  EMPLOYEES_WRITE: 1 << 20,
  STUDENTS_READ: 1 << 9,
  STUDENTS_WRITE: 1 << 21,
  CLASSROOMS_READ: 1 << 10,
  CLASSROOMS_WRITE: 1 << 22,
  SALARY_READ: 1 << 11,
  SALARY_WRITE: 1 << 23,
  ANNOUNCEMENTS_READ: 1 << 12,
  ANNOUNCEMENTS_WRITE: 1 << 24,
  SETTINGS_READ: 1 << 15,
  SETTINGS_WRITE: 1 << 25,
  USER_MANAGEMENT_READ: 1 << 16,
  USER_MANAGEMENT_WRITE: 1 << 26,
  ACTIVITY_READ: 1 << 27,
  ACTIVITY_WRITE: 1 << 28,
  DISMISSAL_CALLS_READ: 2 ** 29,
  DISMISSAL_CALLS_WRITE: 2 ** 30,
  FEES_READ: 2 ** 31,
  FEES_WRITE: 2 ** 32,
  RECRUITMENT_READ: 2 ** 33,
  RECRUITMENT_WRITE: 2 ** 34,
  ACTIVITY_PAYMENT_APPROVE: 2 ** 35,
  // 學生生命週期追蹤（Phase A）
  STUDENTS_LIFECYCLE_WRITE: 2 ** 36,
  GUARDIANS_READ: 2 ** 37,
  GUARDIANS_WRITE: 2 ** 38,
  RECRUITMENT_CONVERT: 2 ** 39,
}

export const ROUTE_PERMISSION_RULES = [
  { path: '/', permission: 'DASHBOARD' },
  { path: '/approvals', permission: 'APPROVALS' },
  { path: '/calendar', permission: 'CALENDAR' },
  { path: '/schedule', permission: 'SCHEDULE' },
  { path: '/attendance', permission: 'ATTENDANCE_READ' },
  { path: '/leaves', permission: 'LEAVES_READ' },
  { path: '/meetings', permission: 'MEETINGS' },
  { path: '/employees', permission: 'EMPLOYEES_READ' },
  { path: '/students', permission: 'STUDENTS_READ' },
  { path: '/students/profile', permission: 'STUDENTS_READ', prefix: true },
  { path: '/classrooms', permission: 'CLASSROOMS_READ' },
  { path: '/salary', permission: 'SALARY_READ' },
  { path: '/announcements', permission: 'ANNOUNCEMENTS_READ' },
  { path: '/reports', permission: 'REPORTS' },
  { path: '/audit-logs', permission: 'AUDIT_LOGS' },
  { path: '/settings', permission: 'SETTINGS_READ' },
  { path: '/dev/salary', permission: 'SALARY_READ' },
  { path: '/activity/dashboard', permission: 'ACTIVITY_READ' },
  { path: '/activity/registrations', permission: 'ACTIVITY_READ' },
  { path: '/activity/pos', permission: 'ACTIVITY_WRITE' },
  { path: '/activity/pos/approval', permission: 'ACTIVITY_PAYMENT_APPROVE' },
  { path: '/activity/courses', permission: 'ACTIVITY_READ' },
  { path: '/activity/supplies', permission: 'ACTIVITY_READ' },
  { path: '/activity/inquiries', permission: 'ACTIVITY_READ' },
  { path: '/activity/settings', permission: 'ACTIVITY_WRITE' },
  { path: '/activity/changes', permission: 'ACTIVITY_READ' },
  { path: '/fees', permission: 'FEES_READ' },
  { path: '/student-enrollment', permission: 'STUDENTS_READ' },
  { path: '/recruitment', permission: 'RECRUITMENT_READ' },
  { path: '/recruitment-ivykids', permission: 'RECRUITMENT_READ' },
]

export const TEACHER_PORTAL_ROUTES = [
  '/portal',
  '/portal/attendance',
  '/portal/leave',
  '/portal/overtime',
  '/portal/schedule',
  '/portal/anomalies',
  '/portal/students',
  '/portal/calendar',
  '/portal/salary',
  '/portal/announcements',
  '/portal/profile',
]
