/**
 * Typed helpers on top of `schema.d.ts` (auto-generated by openapi-typescript).
 *
 * Use these aliases in JSDoc to get IDE-level type checking on `.js` files
 * without migrating the codebase to TypeScript.
 *
 *   import('./_generated/typed').ApiResponse<'/employees', 'get'>
 *   import('./_generated/typed').ApiBody<'/employees', 'post'>
 *   import('./_generated/typed').ApiQuery<'/employees', 'get'>
 *   import('./_generated/typed').ApiPath<'/employees/{employee_id}', 'get'>
 *   import('./_generated/typed').AxiosResp<'/employees', 'get'>
 *
 * Why `AxiosResp` matters: ivy-frontend's axios wrapper does NOT unwrap
 * `.data`. Callers receive `AxiosResponse<T>` and must access `res.data`.
 * `ApiResponse<>` gives you the inner body type; `AxiosResp<>` wraps it
 * with `Promise<AxiosResponse<T>>` so JSDoc `@returns` matches reality.
 */
import type { AxiosResponse } from "axios";
import type { paths } from "./schema";

/** All HTTP methods we expose. */
export type ApiMethod =
  | "get"
  | "post"
  | "put"
  | "patch"
  | "delete";

/** Paths (post-`/api`-stripped) declared by the FastAPI backend. */
export type ApiPaths = keyof paths;

/** Methods that actually exist on a given path. */
export type ApiMethodsOf<P extends ApiPaths> = Extract<
  keyof paths[P],
  ApiMethod
>;

type OpOf<P extends ApiPaths, M extends ApiMethodsOf<P>> =
  paths[P][M] extends infer Op ? Op : never;

type JsonContent<R> = R extends {
  content: { "application/json": infer J };
}
  ? J
  : never;

type SuccessKeys = 200 | 201 | 202 | 204;

/**
 * Success response body (JSON) for a given path+method.
 *
 * If multiple 2xx codes are defined, returns a union of their bodies.
 * If the endpoint has no JSON body (e.g. 204 No Content), resolves to `never`
 * for that branch, leaving you with only the JSON branches.
 */
export type ApiResponse<
  P extends ApiPaths,
  M extends ApiMethodsOf<P>
> = OpOf<P, M> extends { responses: infer R }
  ? {
      [K in keyof R & SuccessKeys]: JsonContent<R[K]>;
    }[keyof R & SuccessKeys]
  : never;

/** JSON request body for a given path+method (never if endpoint has no body). */
export type ApiBody<
  P extends ApiPaths,
  M extends ApiMethodsOf<P>
> = OpOf<P, M> extends { requestBody: infer RB }
  ? RB extends { content: { "application/json": infer J } }
    ? J
    : never
  : never;

/** Query string params (`?foo=bar`) — undefined if endpoint defines none. */
export type ApiQuery<
  P extends ApiPaths,
  M extends ApiMethodsOf<P>
> = OpOf<P, M> extends { parameters: { query?: infer Q } } ? Q : never;

/** Path params (`{employee_id}` etc.) — undefined if endpoint defines none. */
export type ApiPath<
  P extends ApiPaths,
  M extends ApiMethodsOf<P>
> = OpOf<P, M> extends { parameters: { path?: infer P2 } } ? P2 : never;

/**
 * What the axios wrapper actually returns: `Promise<AxiosResponse<Body>>`.
 * Use this in `@returns` so callers correctly see `.data` on the result.
 */
export type AxiosResp<
  P extends ApiPaths,
  M extends ApiMethodsOf<P>
> = Promise<AxiosResponse<ApiResponse<P, M>>>;

/** Named schema component (e.g. `EmployeeCreate`, `HTTPValidationError`). */
import type { components } from "./schema";
export type Schema<K extends keyof components["schemas"]> =
  components["schemas"][K];
